<a href="https://colab.research.google.com/github/Abrahamjondev/ai_foundation/blob/main/students_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("student_performance.csv")
print("Dataset shape (rows, columns): ", df.shape)
print("============================================================================")
print("column name:", df.columns.tolist())
print("============================================================================")
print("First 5 rows of the dataset:")
print(df.head())
print("============================================================================")
print("Summary description of the dataset")
print(df.describe())
print("============================================================================")
print("Data types and null info")
print(df.info())

Dataset shape (rows, columns):  (1000000, 6)
============================================================================
column name: ['student_id', 'weekly_self_study_hours', 'attendance_percentage', 'class_participation', 'total_score', 'grade']
============================================================================
First 5 rows of the dataset:
   student_id  weekly_self_study_hours  attendance_percentage  \
0           1                     18.5                   95.6
1           2                     14.0                   80.0
2           3                     19.5                   86.3
3           4                     25.7                   70.2
4           5                     13.4                   81.9

   class_participation  total_score grade
0                  3.8         97.9     A
1                  2.5         83.9     B
2                  5.3        100.0     A
3                  7.0        100.0     A
4                  6.9         92.0     A
============================================================================
Summary description of the dataset
           student_id  weekly_self_study_hours  attendance_percentage  \
count  1000000.000000           1000000.000000         1000000.000000
mean    500000.500000                15.029127              84.711046
std     288675.278933                 6.899431               9.424143
min          1.000000                 0.000000              50.000000
25%     250000.750000                10.300000              78.300000
50%     500000.500000                15.000000              85.000000
75%     750000.250000                19.700000              91.800000
max    1000000.000000                40.000000             100.000000

       class_participation     total_score
count       1000000.000000  1000000.000000
mean              5.985203       84.283845
std               1.956421       15.432969
min               0.000000        9.400000
25%               4.700000       73.900000
50%               6.000000       87.500000
75%               7.300000      100.000000
max              10.000000      100.000000
============================================================================
Data types and null info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 6 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   student_id               1000000 non-null  int64
 1   weekly_self_study_hours  1000000 non-null  float64
 2   attendance_percentage    1000000 non-null  float64
 3   class_participation      1000000 non-null  float64
 4   total_score              1000000 non-null  float64
 5   grade                    1000000 non-null  object
dtypes: float64(4), int64(1), object(1)
memory usage: 45.8+ MB
None

In [ ]:
print("============================================================================")
print("Average score by columns:")
df[["class_participation", "attendance_percentage", "total_score"]].mean()

============================================================================
Average score by columns:

class_participation       5.985203
attendance_percentage    84.711046
total_score              84.283845
dtype: float64

In [ ]:
print("============================================================================")
print(" Maximumer sentage  and total score by columns:")
df[["class_participation", "attendance_percentage", "total_score"]].max()

============================================================================
 Average per sentage  and total score by columns:

class_participation       10.0
attendance_percentage    100.0
total_score              100.0
dtype: float64

In [ ]:
print("============================================================================")
print(" Minnimumsentage  and minimum score by columns:")
df[["class_participation", "attendance_percentage", "total_score"]].min()

============================================================================
 Minnimumsentage  and minimum score by columns:

class_participation       0.0
attendance_percentage    50.0
total_score               9.4
dtype: float64

In [ ]:
print("============================================================================")
print("Corrolation:")
df[["class_participation", "attendance_percentage", "total_score"]].corr()

============================================================================
Corrolation:

                       class_participation  attendance_percentage  total_score
class_participation               1.000000              -0.000043     0.000684
attendance_percentage            -0.000043               1.000000    -0.001014
total_score                       0.000684              -0.001014     1.000000

In [ ]:
df["total result"] = df[["class_participation", "attendance_percentage", "total_score"]].sum(axis=1)
# print("tiral result")
df["average score"] = df["total_score"] / 2
df["passed"] = np.where(df["average score"] >= 45, "YES", "NO")
print("New columns preview (result, average, passed)")
print(df[["total result", "average score", "passed"]].head(10))

New columns preview (result, average, passed)
   total result  average score passed
0         197.3          48.95    YES
1         166.4          41.95     NO
2         191.6          50.00    YES
3         177.2          50.00    YES
4         180.8          46.00    YES
5         167.6          48.75    YES
6         187.7          50.00    YES
7         200.1          48.05    YES
8         178.0          34.90     NO
9         153.9          40.15     NO

In [ ]:
weekly_self_study_hours = df.groupby('weekly_self_study_hours')[["class_participation", "attendance_percentage", "total_score"]].mean()
print("student score by test preperation course:")
print(weekly_self_study_hours)

# student id

studentId = df.groupby("student_id")[["class_participation", "attendance_percentage", "total_score"]].mean()
print("student score by test preperation course:")
print(studentId)

# Who passed vs failed

pass_rate = df["passed"].value_counts(normalize=True)*100
print("Pass rate:\n", pass_rate)

student score by test preperation course:
                         class_participation  attendance_percentage  \
weekly_self_study_hours
0.0                                 6.004802              84.761048
0.1                                 6.057515              85.372546
0.2                                 6.037842              84.287762
0.3                                 5.974810              85.215478
0.4                                 5.924363              85.225000
...                                      ...                    ...
39.6                                6.266667              85.433333
39.7                                5.377778              87.833333
39.8                                6.200000              82.973684
39.9                                6.520000              83.480000
40.0                                6.253012              84.457831

                         total_score
weekly_self_study_hours
0.0                        50.109975
0.1                        49.791871
0.2                        50.770370
0.3                        50.623976
0.4                        50.665764
...                              ...
39.6                      100.000000
39.7                      100.000000
39.8                      100.000000
39.9                      100.000000
40.0                      100.000000

[401 rows x 3 columns]
student score by test preperation course:
            class_participation  attendance_percentage  total_score
student_id
1                           3.8                   95.6         97.9
2                           2.5                   80.0         83.9
3                           5.3                   86.3        100.0
4                           7.0                   70.2        100.0
5                           6.9                   81.9         92.0
...                         ...                    ...          ...
999996                      4.8                   95.5        100.0
999997                      6.7                   82.7         88.3
999998                      5.8                   85.1         87.9
999999                      5.3                   90.0        100.0
1000000                     4.1                   84.6        100.0

[1000000 rows x 3 columns]
Pass rate:
 passed
NO     54.8622
YES    45.1378
Name: proportion, dtype: float64

In [ ]:
#  convert scores to numpy array
scores = df[["class_participation", "attendance_percentage", "total_score"]].values

# Mean, std Deviation
print("Numpy Mean:", np.mean(scores, axis=0))
print("Numpy Std:", np.std(scores, axis=0))

# ? Z-score (normalize)
z_score = (scores - np.mean(scores, axis=0)) / np.std(scores, axis=0)
print("Z-sciore (normalize numbers)")
print(z_score[:5])

Numpy Mean: [ 5.9852026 84.711046  84.2838453]
Numpy Std: [ 1.95641953  9.42413867 15.43296106]
Z-sciore (normalize numbers)
[[-1.11693968  1.15543228  0.88227753]
 [-1.78141884 -0.49989141 -0.02487179]
 [-0.35023296  0.16860469  1.01834992]
 [ 0.51870132 -1.53977424  1.01834992]
 [ 0.46758754 -0.29828148  0.49997889]]

In [ ]:
#  How many student scored above 90 average

top_scores = df[df["average score"] >= 90]
print("Top scored student above 90", len(top_scores))

#  How many studens failed

failed = df[df["passed"] == "No"]
print("Failed from exam:", len(failed))

Top scored student above 90 0
Failed from exam: 0